export const FESTIVAL_EVENTS = [
  '1 Min Games',
  'Antakshari',
  'Badminton',
  'CGT',
  'Carrom',
  'Chess',
  'Couple Games',
  'Drawing',
  'Fancy Dress',
  'Fashion Show',
  'Fun Fair',
  'Housie',
  'Limbu Chamcha',
  'Musical Chair',
  'Rangoli',
  'Running Race',
  'Slow Cycling',
  'TT',
];
